@hostname=http://localhost
@port=5000
@host={{hostname}}:{{port}}
@admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODdiMTIxNTZmYzU1ZjhmYWUyYWNlMmMiLCJpYXQiOjE3NTI4OTYwMjd9.rnplrcU8tB0JJGCgyTOEAI4aYgRyq9umqkC8pxZXYlk

### Server status

GET {{host}}/status

### Register new user

POST {{host}}/user/register
Content-Type: application/json

{
  "username": "Ruggy",
  "password": "@@@@@11111aaaBBBBB"
}

### Login

POST {{host}}/user/login
Content-Type: application/json

{
  "username": "Ruggy",
  "password": "@@@@@11111aaaBBBBB"
}

### Profile

GET {{host}}/user/profile
Authorization: Bearer {{admin_token}}